name: "Build"
on: [ push ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v1
        id: pages
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages